- name: install and start nginx
  host: frontend
  tasks:
  - name: installnginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name:  start nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes